"""The repository is source, not an artifact store.

`eval/` accumulated 427 KB of committed scratch -- intermediate model-card
renders and copies of result files that are already published on the Hub. It is
regenerated by every evaluation run, so tracking it guarantees the copy in git
and the copy on the Hub disagree.
"""

import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def tracked_files() -> list[str]:
    out = subprocess.run(["git", "ls-files"], cwd=ROOT, capture_output=True,
                         text=True, check=True)
    return out.stdout.splitlines()


def test_no_generated_evaluation_artifacts_are_tracked():
    tracked = [f for f in tracked_files() if f.startswith("eval/")]
    assert tracked == [], (
        f"{len(tracked)} generated files under eval/ are tracked; they are "
        "published on the Hub and regenerated by every run"
    )


def test_eval_is_ignored_so_it_cannot_come_back():
    result = subprocess.run(["git", "check-ignore", "-q", "eval/scratch.json"],
                            cwd=ROOT)
    assert result.returncode == 0, "eval/ must be gitignored"
