"""Count candidate numeral forms in real Mongolian, so a speaker confirms rather
than recalls.

`SUFFIXED_FORMS` needs one row per (numeral, written suffix) and nothing in this
repository can derive them -- see docs/normaliser-review.md. What a corpus *can*
do is say which candidate spellings actually occur and how often, which turns
"what is the dative of тав?" into "is it тавд (19) or таванд (2)?".

    python scripts/attest_forms.py                  # 4000 Wikipedia articles
    python scripts/attest_forms.py --articles 20000

**The counts are evidence, not answers, and they are not safe to paste into the
table.** Three reasons, all visible in the output:

  homographs      "зуун" is both "hundred" and "century", so "зуунд" is inflated
                  by every "19-р зуунд" in the corpus;
  wrong reading   a form can be frequent for a sense that is not the one being
                  expanded -- "гуравт" may be "in third place" rather than the
                  dative of three;
  silence         several numerals never appear in a given case at all, and a
                  zero here means the corpus is quiet, not that no form exists.

The alternation is the clearest warning: the dative surfaces as -т after some
stems and -д after others with no pattern this script can justify, which is
exactly the kind of thing a table is for.
"""

import argparse
import collections
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO))

from oron_tts.text.numbers import ABLATIVE  # noqa: E402

WORD = re.compile(r"[а-яөүё]+")

# Candidate spellings per numeral stem, per case. Generated by hand from the
# shapes Mongolian uses; the corpus decides which are real.
CANDIDATES: dict[str, dict[str, list[str]]] = {
    "dative": {
        "нэг": ["нэгд", "нэгэнд", "нэгнд", "нэгт"],
        "хоёр": ["хоёрт", "хоёрд", "хоёронд"],
        "гурав": ["гуравт", "гурванд", "гуравд"],
        "дөрөв": ["дөрөвт", "дөрвөнд", "дөрөвд"],
        "тав": ["тавд", "таванд", "тавт"],
        "зургаа": ["зургаад", "зургаанд", "зургаат"],
        "долоо": ["долоод", "долоонд", "долоот"],
        "найм": ["наймд", "найманд", "наймт"],
        "ес": ["есд", "есөнд", "ест"],
        "арав": ["аравд", "арванд", "аравт"],
        "хорь": ["хорьд", "хоринд", "хорид"],
        "зуу": ["зуунд", "зууд", "зуут"],
        "мянга": ["мянганд", "мянгад", "мянгат"],
    },
    "genitive": {
        "нэг": ["нэгний", "нэгийн"],
        "хоёр": ["хоёрын", "хоёрны"],
        "гурав": ["гурвын", "гуравын", "гурваны"],
        "дөрөв": ["дөрвийн", "дөрөвний"],
        "тав": ["тавын", "таваны"],
        "зургаа": ["зургаагийн", "зургааны"],
        "долоо": ["долоогийн", "долооны"],
        "арав": ["аравын", "арваны"],
        "хорь": ["хорийн", "хорины"],
        "зуу": ["зуун", "зууны"],
        "мянга": ["мянгын", "мянганы"],
    },
    "accusative": {
        "нэг": ["нэгийг", "нэгыг"],
        "хоёр": ["хоёрыг", "хоёрийг"],
        "гурав": ["гурвыг", "гуравыг"],
        "тав": ["тавыг", "таваныг"],
        "хорь": ["хорийг", "хориныг"],
        "зуу": ["зууг", "зууныг"],
    },
}

# Words whose count is inflated by an unrelated sense. Reported, not silently
# dropped: a reader should see why the number is large.
HOMOGRAPHS = {
    "зуунд": "зуун also means century",
    "зууны": "зуун also means century",
    "зуун": "zuun also means century, and is the attributive of 100",
    "мянгад": "also the approximative of 1000 in decade names",
    "мянганы": "also millennium",
}


def load_corpus(articles: int) -> str:
    from datasets import load_dataset

    stream = load_dataset(
        "wikimedia/wikipedia", "20231101.mn", split="train", streaming=True
    )
    out = []
    for i, row in enumerate(stream):
        if i >= articles:
            break
        out.append(row["text"])
    return "\n".join(out)


def report(counts: collections.Counter, case: str) -> None:
    print(f"\n## {case}\n")
    print(f"  {'stem':<8}{'attested (count)':<46}note")
    for stem, forms in CANDIDATES[case].items():
        scored = sorted(((f, counts[f]) for f in forms), key=lambda kv: -kv[1])
        shown = "  ".join(f"{f}={n}" for f, n in scored if n) or "-"
        top, n = scored[0]
        runner = scored[1][1] if len(scored) > 1 else 0
        if n == 0:
            note = "corpus is silent"
        elif top in HOMOGRAPHS:
            note = f"inflated: {HOMOGRAPHS[top]}"
        elif n >= 5 and n >= 3 * max(runner, 1):
            note = "one form dominates"
        else:
            note = "no clear winner"
        print(f"  {stem:<8}{shown:<46}{note}")


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--articles", type=int, default=4000)
    ap.add_argument("--corpus", type=Path, default=None,
                    help="A text file to count instead of downloading Wikipedia")
    args = ap.parse_args()

    blob = (args.corpus.read_text(encoding="utf-8") if args.corpus
            else load_corpus(args.articles)).lower()
    counts = collections.Counter(WORD.findall(blob))
    print(f"{sum(counts.values()):,} word tokens, {len(counts):,} types")

    for case in CANDIDATES:
        report(counts, case)

    print("\n## the ablative table this repository already ships\n")
    print("  Counts for the forms in ABLATIVE, so a wrong entry shows up as a")
    print("  form nobody writes.\n")
    for stem, form in sorted(ABLATIVE.items()):
        n = counts[form]
        flag = "" if n else "   <- unattested here"
        print(f"  {stem:<8} {form:<14} {n:>5}{flag}")

    print("\nNothing above may be copied into SUFFIXED_FORMS without a speaker "
          "confirming it. See the caveats at the top of this file.")


if __name__ == "__main__":
    main()
